# Generated by Django 5.0.2 on 2024-03-03 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='servico',
            new_name='servico_id',
        ),
    ]
